version: '3.1'
services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mon_projet
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  my-db:
